[tool.black]
line-length = 115
target-version = ['py37']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | \.idea
    | \.pytest_cache
    | \__pycache__
    | _build
    | buck-out
    | build
    | dist
    | docs
  )/
  | versioneer.py
  | bluesky_httpserver_bmm/_version.py
)
'''
